### ISSUE TITLE
S6 init issue?

### ISSUE THREAD

**Issue by andriej** [basnijholt/addon-otmonitor#41]
I've reinstalled HA on my host and while trying to install add-on I have an error:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/nginx.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: 14: /etc/cont-init.d/nginx.sh: Permission denied
cont-init: info: /etc/cont-init.d/nginx.sh exited 126
cont-init: info: running /etc/cont-init.d/otmonitor.sh
[20:19:45] INFO: Initializing service configuration.
[20:19:47] INFO: Using manually provided MQTT credentials
[20:19:48] INFO: Finished updating otmonitor config file.
cont-init: info: /etc/cont-init.d/otmonitor.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

which seem to be quite odd?

It's HA OS installation

**Comment by andriej** [comment]
@fliphess I see update in config.json to fix that probably? 
config is:
```
otgw:
  host: REDACTED
  port: REDACTED
  relay_port: 7686
mqtt:
  autoconfig: false
  broker: addon_core_mosquitto
  port: 1883
  username: REDACTED
  password: REDACTED
  client_id: otmonitor
  action_topic: actions/otmonitor
  event_topic: events/central_heating/otmonitor
  data_format: raw
  all_messages: false
  qos: 1
  retransmit: 10
email:
  enable: false
  recipient: recipient_here
  sender: sender_here
  user: user_here
  password: password_here
  server: mail_server_here
  port: 25
  secure: Plain
tspeak:
  enable: false
  key: key_here
  interval: 120
  sync: true
html_templates:
  enabled: false
  editable: false
```
